/**
 * fbx-export.js — Minimal FBX 7.4 ASCII writer for Slate's 3D scenes.
 *
 * Takes an array of plain scene-object descriptors (the same shape that lives
 * in window.slateScene3d.objects) and produces an FBX ASCII string compatible
 * with Blender, Maya, 3ds Max, and Unity import.
 *
 * Triangulates all faces and bakes one Geometry + one Model node per visible
 * object into the scene root.
 */
import * as THREE from 'three';

function _fmt(n) {
  if (!Number.isFinite(n)) return '0';
  // FBX expects plain decimals (no exponents); trim trailing zeros.
  const s = n.toFixed(7);
  return s.replace(/\.?0+$/, '') || '0';
}

function _geometryFor(obj) {
  const p = obj.params || {};
  switch (obj.type) {
    case 'cube':     return new THREE.BoxGeometry(p.size ?? 1, p.size ?? 1, p.size ?? 1);
    case 'sphere':   return new THREE.SphereGeometry(p.radius ?? 0.5, p.widthSegments ?? 24, p.heightSegments ?? 16);
    case 'plane':    return new THREE.PlaneGeometry(p.width ?? 2, p.height ?? 2);
    case 'cylinder': return new THREE.CylinderGeometry(p.radiusTop ?? 0.5, p.radiusBottom ?? 0.5, p.height ?? 1, p.radialSegments ?? 32);
    case 'cone':     return new THREE.ConeGeometry(p.radius ?? 0.5, p.height ?? 1, p.radialSegments ?? 32);
    case 'torus':    return new THREE.TorusGeometry(p.radius ?? 0.5, p.tube ?? 0.18, p.radialSegments ?? 16, p.tubularSegments ?? 32);
    case 'mesh': {
      const g = new THREE.BufferGeometry();
      const md = obj.meshData || { vertices: [], faces: [] };
      if (md.vertices?.length) g.setAttribute('position', new THREE.Float32BufferAttribute(new Float32Array(md.vertices), 3));
      if (md.faces?.length) g.setIndex(md.faces);
      g.computeVertexNormals();
      return g;
    }
    default: return new THREE.BoxGeometry(1, 1, 1);
  }
}

/* Extract { vertices, indices, normals } from a THREE.BufferGeometry. */
function _bake(geo) {
  geo.computeVertexNormals();
  const pos = geo.getAttribute('position');
  const norm = geo.getAttribute('normal');
  const idx = geo.getIndex();
  const verts = new Array(pos.count * 3);
  for (let i = 0; i < pos.count; i++) {
    verts[i * 3]     = pos.getX(i);
    verts[i * 3 + 1] = pos.getY(i);
    verts[i * 3 + 2] = pos.getZ(i);
  }
  let triIndices;
  if (idx) {
    triIndices = new Array(idx.count);
    for (let i = 0; i < idx.count; i++) triIndices[i] = idx.getX(i);
  } else {
    triIndices = new Array(pos.count);
    for (let i = 0; i < pos.count; i++) triIndices[i] = i;
  }
  // Per-polygon-vertex normals (mapping = ByPolygonVertex / Direct).
  const pvNormals = new Array(triIndices.length * 3);
  for (let i = 0; i < triIndices.length; i++) {
    const vi = triIndices[i];
    pvNormals[i * 3]     = norm ? norm.getX(vi) : 0;
    pvNormals[i * 3 + 1] = norm ? norm.getY(vi) : 1;
    pvNormals[i * 3 + 2] = norm ? norm.getZ(vi) : 0;
  }
  return { verts, triIndices, pvNormals };
}

function _polygonVertexIndexArray(triIndices) {
  // FBX flags the last vertex of each polygon by bit-inverting it (~i).
  // We emit triangles, so every 3rd index gets negated.
  const out = new Array(triIndices.length);
  for (let i = 0; i < triIndices.length; i++) {
    const v = triIndices[i];
    out[i] = (i % 3 === 2) ? -(v + 1) : v;
  }
  return out;
}

/** Convert "#7c6aff" → [0.486, 0.416, 1.0] floats in [0..1]. */
function _hexToRgb(hex) {
  const h = (hex || '#7c6aff').replace('#', '');
  const r = parseInt(h.substring(0, 2), 16) / 255;
  const g = parseInt(h.substring(2, 4), 16) / 255;
  const b = parseInt(h.substring(4, 6), 16) / 255;
  return [r, g, b];
}

/* Chunked array writer to avoid million-token-long single lines. */
function _writeNumArray(label, arr, indent) {
  const pad = ' '.repeat(indent);
  const lines = [`${pad}${label}: *${arr.length} {`];
  if (!arr.length) {
    lines.push(`${pad}  a:`);
    lines.push(`${pad}}`);
    return lines.join('\n');
  }
  const chunkSize = 600; // numbers per line; safe for parsers
  for (let i = 0; i < arr.length; i += chunkSize) {
    const slice = arr.slice(i, i + chunkSize);
    const prefix = i === 0 ? 'a: ' : '   ';
    lines.push(`${pad}  ${prefix}${slice.map(_fmt).join(',')}${i + chunkSize < arr.length ? ',' : ''}`);
  }
  lines.push(`${pad}}`);
  return lines.join('\n');
}

function _radToDeg(r) { return r * (180 / Math.PI); }

function exportFbxAscii({ objects = [], creator = 'Slate' } = {}) {
  const now = new Date();
  const ts = {
    Y: now.getFullYear(), M: now.getMonth() + 1, D: now.getDate(),
    h: now.getHours(),    m: now.getMinutes(),   s: now.getSeconds(), ms: now.getMilliseconds(),
  };

  const lines = [];
  // ── Header ──
  lines.push(`; FBX 7.4.0 project file`);
  lines.push(`; Generated by ${creator} (Slate FBX writer)`);
  lines.push(`; ----------------------------------------------------\n`);
  lines.push(`FBXHeaderExtension:  {`);
  lines.push(`  FBXHeaderVersion: 1003`);
  lines.push(`  FBXVersion: 7400`);
  lines.push(`  CreationTimeStamp:  {`);
  lines.push(`    Version: 1000`);
  lines.push(`    Year: ${ts.Y}`);
  lines.push(`    Month: ${ts.M}`);
  lines.push(`    Day: ${ts.D}`);
  lines.push(`    Hour: ${ts.h}`);
  lines.push(`    Minute: ${ts.m}`);
  lines.push(`    Second: ${ts.s}`);
  lines.push(`    Millisecond: ${ts.ms}`);
  lines.push(`  }`);
  lines.push(`  Creator: "${creator} FBX Exporter"`);
  lines.push(`}`);
  lines.push(`GlobalSettings:  {`);
  lines.push(`  Version: 1000`);
  lines.push(`  Properties70:  {`);
  lines.push(`    P: "UpAxis", "int", "Integer", "",1`);
  lines.push(`    P: "UpAxisSign", "int", "Integer", "",1`);
  lines.push(`    P: "FrontAxis", "int", "Integer", "",2`);
  lines.push(`    P: "FrontAxisSign", "int", "Integer", "",1`);
  lines.push(`    P: "CoordAxis", "int", "Integer", "",0`);
  lines.push(`    P: "CoordAxisSign", "int", "Integer", "",1`);
  lines.push(`    P: "OriginalUpAxis", "int", "Integer", "",1`);
  lines.push(`    P: "OriginalUpAxisSign", "int", "Integer", "",1`);
  lines.push(`    P: "UnitScaleFactor", "double", "Number", "",1`);
  lines.push(`    P: "OriginalUnitScaleFactor", "double", "Number", "",1`);
  lines.push(`    P: "AmbientColor", "ColorRGB", "Color", "",0,0,0`);
  lines.push(`    P: "DefaultCamera", "KString", "", "", "Producer Perspective"`);
  lines.push(`    P: "TimeMode", "enum", "", "",6`);
  lines.push(`  }`);
  lines.push(`}`);

  /* ── Definitions ── */
  const visibleObjs = objects.filter(o => o.visible !== false);
  lines.push(`Definitions:  {`);
  lines.push(`  Version: 100`);
  lines.push(`  Count: ${visibleObjs.length * 3 + 1}`);
  lines.push(`  ObjectType: "GlobalSettings" { Count: 1 }`);
  if (visibleObjs.length) {
    lines.push(`  ObjectType: "Geometry" { Count: ${visibleObjs.length} }`);
    lines.push(`  ObjectType: "Model"    { Count: ${visibleObjs.length} }`);
    lines.push(`  ObjectType: "Material" { Count: ${visibleObjs.length} }`);
  }
  lines.push(`}`);

  /* ── Objects ── */
  lines.push(`Objects:  {`);
  /* Assign deterministic numeric IDs from a counter — FBX requires int64. */
  let nextId = 1000000;
  const idFor = new Map(); // objId -> { geomId, modelId, matId }
  for (const obj of visibleObjs) {
    idFor.set(obj.id, {
      geomId:  nextId++,
      modelId: nextId++,
      matId:   nextId++,
    });
  }

  for (const obj of visibleObjs) {
    const { geomId, modelId, matId } = idFor.get(obj.id);
    const cleanName = (obj.name || obj.type || 'Object').replace(/[^A-Za-z0-9_\-]/g, '_');
    const geo = _geometryFor(obj);
    const { verts, triIndices, pvNormals } = _bake(geo);
    geo.dispose?.();

    /* Geometry */
    lines.push(`  Geometry: ${geomId}, "Geometry::${cleanName}", "Mesh" {`);
    lines.push(_writeNumArray(`Vertices`, verts, 4));
    lines.push(_writeNumArray(`PolygonVertexIndex`, _polygonVertexIndexArray(triIndices), 4));
    lines.push(`    GeometryVersion: 124`);
    lines.push(`    LayerElementNormal: 0 {`);
    lines.push(`      Version: 102`);
    lines.push(`      Name: ""`);
    lines.push(`      MappingInformationType: "ByPolygonVertex"`);
    lines.push(`      ReferenceInformationType: "Direct"`);
    lines.push(_writeNumArray(`Normals`, pvNormals, 6));
    lines.push(`    }`);
    lines.push(`    Layer: 0 {`);
    lines.push(`      Version: 100`);
    lines.push(`      LayerElement: { Type: "LayerElementNormal", TypedIndex: 0 }`);
    lines.push(`    }`);
    lines.push(`  }`);

    /* Model node */
    const t = obj.position || [0, 0, 0];
    const r = obj.rotation || [0, 0, 0];
    const s = obj.scale    || [1, 1, 1];
    lines.push(`  Model: ${modelId}, "Model::${cleanName}", "Mesh" {`);
    lines.push(`    Version: 232`);
    lines.push(`    Properties70:  {`);
    lines.push(`      P: "Lcl Translation", "Lcl Translation", "", "A",${_fmt(t[0])},${_fmt(t[1])},${_fmt(t[2])}`);
    lines.push(`      P: "Lcl Rotation",    "Lcl Rotation",    "", "A",${_fmt(_radToDeg(r[0]))},${_fmt(_radToDeg(r[1]))},${_fmt(_radToDeg(r[2]))}`);
    lines.push(`      P: "Lcl Scaling",     "Lcl Scaling",     "", "A",${_fmt(s[0])},${_fmt(s[1])},${_fmt(s[2])}`);
    lines.push(`      P: "DefaultAttributeIndex", "int", "Integer", "",0`);
    lines.push(`    }`);
    lines.push(`    Shading: T`);
    lines.push(`    Culling: "CullingOff"`);
    lines.push(`  }`);

    /* Material */
    const [cr, cg, cb] = _hexToRgb(obj.color);
    lines.push(`  Material: ${matId}, "Material::${cleanName}", "" {`);
    lines.push(`    Version: 102`);
    lines.push(`    ShadingModel: "Lambert"`);
    lines.push(`    MultiLayer: 0`);
    lines.push(`    Properties70:  {`);
    lines.push(`      P: "DiffuseColor", "Color", "", "A",${_fmt(cr)},${_fmt(cg)},${_fmt(cb)}`);
    lines.push(`      P: "Emissive", "Vector3D", "Vector", "",0,0,0`);
    lines.push(`      P: "Ambient", "Vector3D", "Vector", "",0.2,0.2,0.2`);
    lines.push(`      P: "Diffuse", "Vector3D", "Vector", "",${_fmt(cr)},${_fmt(cg)},${_fmt(cb)}`);
    lines.push(`    }`);
    lines.push(`  }`);
  }
  lines.push(`}`);

  /* ── Connections ── */
  lines.push(`Connections:  {`);
  for (const obj of visibleObjs) {
    const { geomId, modelId, matId } = idFor.get(obj.id);
    lines.push(`  ;Model::${obj.name || obj.id}, Model::RootNode`);
    lines.push(`  C: "OO",${modelId},0`);
    lines.push(`  ;Geometry::${obj.name || obj.id}, Model::${obj.name || obj.id}`);
    lines.push(`  C: "OO",${geomId},${modelId}`);
    lines.push(`  ;Material::${obj.name || obj.id}, Model::${obj.name || obj.id}`);
    lines.push(`  C: "OO",${matId},${modelId}`);
  }
  lines.push(`}`);

  return lines.join('\n') + '\n';
}

window.slateExportFbx = exportFbxAscii;
export { exportFbxAscii };
