/**
 * Tiny FBX 7.4 ASCII writer for Slate scenes — no Three.js dependency.
 *
 * Reads from Slate's neutral mesh representation (packages/mesh) +
 * scene Object3D + Material schema (packages/sync-protocol) and produces
 * an FBX string that Blender / Maya / Unity / 3ds Max all import.
 *
 * Ported and cleaned from v1 fbx-export.js, with these improvements:
 *  - per-object transform preserved (v1's import path flattened to identity)
 *  - operates on Mesh (n-gons) — fan-triangulated only at export time
 *  - per-object material color from PBR material if present
 */

import type { Mesh, MeshFace } from '@slate/mesh';
import { triangulateFace } from '@slate/mesh';
import type { Material, Object3D, MeshData } from '@slate/sync-protocol';

export interface FbxExportInput {
  objects: Object3D[];
  meshes: Record<string, MeshData>;
  materials: Record<string, Material>;
  creator?: string;
}

export function exportFbxAscii({
  objects,
  meshes,
  materials,
  creator = 'Slate',
}: FbxExportInput): string {
  const visible = objects.filter((o) => o.visible !== false && o.type !== 'folder' && o.type !== 'empty');

  const lines: string[] = [];
  const now = new Date();

  lines.push(`; FBX 7.4.0 project file`);
  lines.push(`; Generated by ${creator} (Slate FBX writer)`);
  lines.push(`; ----------------------------------------------------\n`);
  lines.push(`FBXHeaderExtension:  {`);
  lines.push(`  FBXHeaderVersion: 1003`);
  lines.push(`  FBXVersion: 7400`);
  lines.push(`  CreationTimeStamp:  {`);
  lines.push(`    Version: 1000`);
  lines.push(`    Year: ${now.getFullYear()}`);
  lines.push(`    Month: ${now.getMonth() + 1}`);
  lines.push(`    Day: ${now.getDate()}`);
  lines.push(`    Hour: ${now.getHours()}`);
  lines.push(`    Minute: ${now.getMinutes()}`);
  lines.push(`    Second: ${now.getSeconds()}`);
  lines.push(`    Millisecond: ${now.getMilliseconds()}`);
  lines.push(`  }`);
  lines.push(`  Creator: "${creator} FBX Exporter"`);
  lines.push(`}`);
  lines.push(`GlobalSettings:  {`);
  lines.push(`  Version: 1000`);
  lines.push(`  Properties70:  {`);
  lines.push(`    P: "UpAxis", "int", "Integer", "",1`);
  lines.push(`    P: "UpAxisSign", "int", "Integer", "",1`);
  lines.push(`    P: "FrontAxis", "int", "Integer", "",2`);
  lines.push(`    P: "FrontAxisSign", "int", "Integer", "",1`);
  lines.push(`    P: "CoordAxis", "int", "Integer", "",0`);
  lines.push(`    P: "CoordAxisSign", "int", "Integer", "",1`);
  lines.push(`    P: "UnitScaleFactor", "double", "Number", "",1`);
  lines.push(`    P: "DefaultCamera", "KString", "", "", "Producer Perspective"`);
  lines.push(`    P: "TimeMode", "enum", "", "",6`);
  lines.push(`  }`);
  lines.push(`}`);

  lines.push(`Definitions:  {`);
  lines.push(`  Version: 100`);
  lines.push(`  Count: ${visible.length * 3 + 1}`);
  lines.push(`  ObjectType: "GlobalSettings" { Count: 1 }`);
  if (visible.length) {
    lines.push(`  ObjectType: "Geometry" { Count: ${visible.length} }`);
    lines.push(`  ObjectType: "Model"    { Count: ${visible.length} }`);
    lines.push(`  ObjectType: "Material" { Count: ${visible.length} }`);
  }
  lines.push(`}`);

  lines.push(`Objects:  {`);
  let nextId = 1_000_000;
  const ids = new Map<string, { geomId: number; modelId: number; matId: number }>();
  for (const o of visible) {
    ids.set(o.id, { geomId: nextId++, modelId: nextId++, matId: nextId++ });
  }

  for (const o of visible) {
    const { geomId, modelId, matId } = ids.get(o.id)!;
    const cleanName = (o.name || o.type || 'Object').replace(/[^A-Za-z0-9_-]/g, '_');
    const md = o.meshId ? meshes[o.meshId] : undefined;
    const mesh: Mesh = md
      ? { vertices: md.vertices.slice(), faces: md.faces.map((f) => ({ v: f.v.slice() })) }
      : { vertices: [], faces: [] };
    const triIdx: number[] = [];
    for (const f of mesh.faces) {
      for (const t of triangulateFace(f as MeshFace)) triIdx.push(...t.v);
    }
    const pvNormals = computePolyVertexNormals(mesh, triIdx);

    lines.push(`  Geometry: ${geomId}, "Geometry::${cleanName}", "Mesh" {`);
    lines.push(writeNumArray('Vertices', mesh.vertices, 4));
    lines.push(writeNumArray('PolygonVertexIndex', polygonVertexIndexArray(triIdx), 4));
    lines.push(`    GeometryVersion: 124`);
    lines.push(`    LayerElementNormal: 0 {`);
    lines.push(`      Version: 102`);
    lines.push(`      Name: ""`);
    lines.push(`      MappingInformationType: "ByPolygonVertex"`);
    lines.push(`      ReferenceInformationType: "Direct"`);
    lines.push(writeNumArray('Normals', pvNormals, 6));
    lines.push(`    }`);
    lines.push(`    Layer: 0 {`);
    lines.push(`      Version: 100`);
    lines.push(`      LayerElement: { Type: "LayerElementNormal", TypedIndex: 0 }`);
    lines.push(`    }`);
    lines.push(`  }`);

    const t = o.transform.position;
    const r = o.transform.rotation;
    const s = o.transform.scale;
    lines.push(`  Model: ${modelId}, "Model::${cleanName}", "Mesh" {`);
    lines.push(`    Version: 232`);
    lines.push(`    Properties70:  {`);
    lines.push(
      `      P: "Lcl Translation", "Lcl Translation", "", "A",${fmt(t.x)},${fmt(t.y)},${fmt(t.z)}`,
    );
    lines.push(
      `      P: "Lcl Rotation",    "Lcl Rotation",    "", "A",${fmt(radToDeg(r.x))},${fmt(radToDeg(r.y))},${fmt(radToDeg(r.z))}`,
    );
    lines.push(
      `      P: "Lcl Scaling",     "Lcl Scaling",     "", "A",${fmt(s.x)},${fmt(s.y)},${fmt(s.z)}`,
    );
    lines.push(`      P: "DefaultAttributeIndex", "int", "Integer", "",0`);
    lines.push(`    }`);
    lines.push(`    Shading: T`);
    lines.push(`    Culling: "CullingOff"`);
    lines.push(`  }`);

    const mat = o.materialId ? materials[o.materialId] : undefined;
    const [cr, cg, cb] = hexToRgb(mat?.color ?? '#7c6aff');
    lines.push(`  Material: ${matId}, "Material::${cleanName}", "" {`);
    lines.push(`    Version: 102`);
    lines.push(`    ShadingModel: "Lambert"`);
    lines.push(`    MultiLayer: 0`);
    lines.push(`    Properties70:  {`);
    lines.push(`      P: "DiffuseColor", "Color", "", "A",${fmt(cr)},${fmt(cg)},${fmt(cb)}`);
    lines.push(`      P: "Emissive", "Vector3D", "Vector", "",0,0,0`);
    lines.push(`      P: "Ambient", "Vector3D", "Vector", "",0.2,0.2,0.2`);
    lines.push(`      P: "Diffuse", "Vector3D", "Vector", "",${fmt(cr)},${fmt(cg)},${fmt(cb)}`);
    lines.push(`    }`);
    lines.push(`  }`);
  }
  lines.push(`}`);

  lines.push(`Connections:  {`);
  for (const o of visible) {
    const { geomId, modelId, matId } = ids.get(o.id)!;
    lines.push(`  C: "OO",${modelId},0`);
    lines.push(`  C: "OO",${geomId},${modelId}`);
    lines.push(`  C: "OO",${matId},${modelId}`);
  }
  lines.push(`}`);

  return lines.join('\n') + '\n';
}

function fmt(n: number): string {
  if (!Number.isFinite(n)) return '0';
  const s = n.toFixed(7);
  return s.replace(/\.?0+$/, '') || '0';
}

function radToDeg(r: number): number {
  return r * (180 / Math.PI);
}

function hexToRgb(hex: string): [number, number, number] {
  const h = (hex || '#7c6aff').replace('#', '');
  return [
    parseInt(h.substring(0, 2) || 'ff', 16) / 255,
    parseInt(h.substring(2, 4) || 'ff', 16) / 255,
    parseInt(h.substring(4, 6) || 'ff', 16) / 255,
  ];
}

function polygonVertexIndexArray(triIdx: number[]): number[] {
  // FBX marks the last vertex of each polygon by bit-inverting (~i).
  return triIdx.map((v, i) => (i % 3 === 2 ? -(v + 1) : v));
}

function writeNumArray(label: string, arr: number[], indent: number): string {
  const pad = ' '.repeat(indent);
  if (!arr.length) return `${pad}${label}: *0 {\n${pad}  a:\n${pad}}`;
  const chunkSize = 600;
  const lines: string[] = [`${pad}${label}: *${arr.length} {`];
  for (let i = 0; i < arr.length; i += chunkSize) {
    const slice = arr.slice(i, i + chunkSize);
    const prefix = i === 0 ? 'a: ' : '   ';
    lines.push(`${pad}  ${prefix}${slice.map(fmt).join(',')}${i + chunkSize < arr.length ? ',' : ''}`);
  }
  lines.push(`${pad}}`);
  return lines.join('\n');
}

function computePolyVertexNormals(mesh: Mesh, triIdx: number[]): number[] {
  if (!mesh.vertices.length || !triIdx.length) return [];
  const vCount = mesh.vertices.length / 3;
  const sum = new Float32Array(vCount * 3);
  for (let i = 0; i < triIdx.length; i += 3) {
    const ia = triIdx[i]!;
    const ib = triIdx[i + 1]!;
    const ic = triIdx[i + 2]!;
    const ax = mesh.vertices[ia * 3]!,
      ay = mesh.vertices[ia * 3 + 1]!,
      az = mesh.vertices[ia * 3 + 2]!;
    const bx = mesh.vertices[ib * 3]!,
      by = mesh.vertices[ib * 3 + 1]!,
      bz = mesh.vertices[ib * 3 + 2]!;
    const cx = mesh.vertices[ic * 3]!,
      cy = mesh.vertices[ic * 3 + 1]!,
      cz = mesh.vertices[ic * 3 + 2]!;
    const ux = bx - ax,
      uy = by - ay,
      uz = bz - az;
    const vx = cx - ax,
      vy = cy - ay,
      vz = cz - az;
    const nx = uy * vz - uz * vy;
    const ny = uz * vx - ux * vz;
    const nz = ux * vy - uy * vx;
    for (const ii of [ia, ib, ic]) {
      sum[ii * 3] = (sum[ii * 3] ?? 0) + nx;
      sum[ii * 3 + 1] = (sum[ii * 3 + 1] ?? 0) + ny;
      sum[ii * 3 + 2] = (sum[ii * 3 + 2] ?? 0) + nz;
    }
  }
  // Normalize per vertex.
  for (let i = 0; i < vCount; i++) {
    const l =
      Math.hypot(sum[i * 3]!, sum[i * 3 + 1]!, sum[i * 3 + 2]!) || 1;
    sum[i * 3] = (sum[i * 3] ?? 0) / l;
    sum[i * 3 + 1] = (sum[i * 3 + 1] ?? 0) / l;
    sum[i * 3 + 2] = (sum[i * 3 + 2] ?? 0) / l;
  }
  const pv = new Array<number>(triIdx.length * 3);
  for (let i = 0; i < triIdx.length; i++) {
    const v = triIdx[i]!;
    pv[i * 3] = sum[v * 3]!;
    pv[i * 3 + 1] = sum[v * 3 + 1]!;
    pv[i * 3 + 2] = sum[v * 3 + 2]!;
  }
  return pv;
}
